# Generated by Django 5.1.2 on 2024-11-03 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('nota_portugues', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_matematica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulados', to='app.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.aluno')),
                ('nome_pai', models.CharField(max_length=100)),
            ],
            bases=('app.aluno',),
        ),
        migrations.CreateModel(
            name='ColegioAplicacao',
            fields=[
                ('simulado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.simulado')),
                ('peso_matematica', models.FloatField()),
                ('peso_portugues', models.FloatField()),
            ],
            bases=('app.simulado',),
        ),
        migrations.CreateModel(
            name='ColegiosMilitares',
            fields=[
                ('simulado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.simulado')),
                ('peso', models.FloatField()),
                ('media', models.FloatField()),
            ],
            bases=('app.simulado',),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100)),
                ('professor', models.ManyToManyField(related_name='professor_turma', to='app.professor')),
                ('simulados', models.ManyToManyField(related_name='turmas', to='app.simulado')),
            ],
        ),
    ]
