# Generated by Django 5.1.2 on 2024-11-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulado',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='simulado',
            name='data',
        ),
        migrations.AddField(
            model_name='simulado',
            name='alunos',
            field=models.ManyToManyField(related_name='simulados', to='app.aluno'),
        ),
        migrations.AddField(
            model_name='simulado',
            name='nome',
            field=models.CharField(default='Simulado padrão', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulado',
            name='nota_matematica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulado',
            name='nota_portugues',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
