# Generated by Django 5.1.2 on 2024-11-03 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_simulado_aluno_remove_simulado_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulado',
            name='nota_matematica',
        ),
        migrations.RemoveField(
            model_name='simulado',
            name='nota_portugues',
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_portugues', models.FloatField(blank=True, null=True)),
                ('nota_matematica', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.simulado')),
            ],
        ),
    ]
