# Generated by Django 5.0.6 on 2024-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_nota_simulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='simulados',
            field=models.ManyToManyField(blank=True, null=True, related_name='turmas', to='app.simulado'),
        ),
    ]
