# Generated by Django 5.0.6 on 2024-11-28 03:06

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_simulado_nota_matematica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('questoes_dificeis', models.IntegerField()),
                ('questoes_faceis', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='colegiosmilitares',
            name='simulado_ptr',
        ),
        migrations.AlterModelOptions(
            name='pai',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='pai',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='professor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pai',
            name='aluno_ptr',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='app.turma'),
        ),
        migrations.AddField(
            model_name='pai',
            name='alunos',
            field=models.ManyToManyField(related_name='pais', to='app.aluno'),
        ),
        migrations.AddField(
            model_name='simulado',
            name='peso_matematica',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='simulado',
            name='peso_portugues',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(related_name='turmas', to='app.professor'),
        ),
        migrations.DeleteModel(
            name='ColegioAplicacao',
        ),
        migrations.DeleteModel(
            name='ColegiosMilitares',
        ),
    ]
