# Generated by Django 5.1.3 on 2024-11-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_turma_simulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(null=True, related_name='turmas', to='app.professor'),
        ),
    ]
